<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Migrations\Migration;

class QuickMigration extends Migration
{
    /**
     * Run the raw SQL dump file generated by artisan db:dump
     *
     * @return void
     */
    public function up()
    {
        DB::unprepared(file_get_contents(__DIR__ . '/sql.dump'));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
    }
}